config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users;
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, type: String
  field :name, type: String
  field :lastname, type: String
  field :country, type: String
  field :city, type: String
  field :username, type: String
  field :password, type: String
  field :currency, type: String
  field :balance, type: Float
  field :birthday, type: Date
  field :email, type: String
  field :phone, type: String
  field :platform, type: String
  field :status, type: String

  validates :name, :lastname, :email, :platform, presence: true
  validates :email, uniqueness: { scope: :platform, message: "debe ser único en la plataforma" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:code, :name, :lastname, :country, :city, :username, :password, :currency, :balance, :birthday, :email, :phone, :platform, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mongo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :currency, style: "display: block" %>
    <%= form.text_field :currency %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.text_field :platform %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Code:</strong>
    <%= user.code %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= user.lastname %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= user.country %>
  </p>

  <p>
    <strong>City:</strong>
    <%= user.city %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= user.currency %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= user.balance %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= user.birthday %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= user.platform %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= user.status %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->



<table class="user-table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>País</th>
      <th>Ciudad</th>
      <th>Plataforma</th>
      <th>Nombre de Usuario</th>
      <th>Correo Electrónico</th>
      <th>Acciones</th> <!-- Nueva columna para botones -->
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.code %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.country %></td>
        <td><%= user.city %></td>
        <td><%= user.platform %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Ver', user_path(user), class: 'btn btn-info' %>
          <%= link_to 'Editar', edit_user_path(user), class: 'btn btn-warning' %>
          <%= link_to 'Eliminar', user_path(user), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>